baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Sparkurity by Juris Puce'

# Main menu configuration
[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    name = 'Resources & Events'
    url = '/blog/'
    weight = 20
  [[menu.main]]
    name = 'Training Paths'
    url = '/training/'
    weight = 30
